### ISSUE TITLE
Ошибка при скачивании версии

### ISSUE THREAD

**Issue by Belkin1337** [Seeroy/FrogLauncher#1]
Скачиваемая версия: Fabric 1.20.1 

Ошибка:
Uncaught exception in thread "main"
java.lang.NoClassDefFoundError: net/fabricmc/mapping/tree/TinyMappingFactory
	at net.fabricmc.loader.impl.game.LoaderLibrary.<clinit>(LoaderLibrary.java:40)
	at net.fabricmc.loader.impl.game.LibClassifier.<init>(LibClassifier.java:100)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:171)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:177)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.mapping.tree.TinyMappingFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

**Comment by Seeroy** [comment]
Пожалуйста предоставьте crash-report (если он присутствует) или файл лога игры, а так же список установленных модов

**Comment by Belkin1337** [comment]
> 

Модов нет, ну кроме как Fabric API.

[21:06:35] [ERROR] [FabricLoader/]: Uncaught exception in thread "main"
java.lang.NoClassDefFoundError: net/fabricmc/mapping/tree/TinyMappingFactory
	at net.fabricmc.loader.impl.game.LoaderLibrary.<clinit>(LoaderLibrary.java:40)
	at net.fabricmc.loader.impl.game.LibClassifier.<init>(LibClassifier.java:100)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:171)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:177)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.mapping.tree.TinyMappingFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

**Comment by Seeroy** [comment]
Благодарю за ответ. Отправьте ещё скриншот настроек из лаунчера. В течение нескольких дней проверю информацию

**Comment by Belkin1337** [comment]
> Благодарю за ответ. Отправьте ещё скриншот настроек из лаунчера. В течение нескольких дней проверю информацию

https://imgur.com/5uCzjKz

**Comment by Seeroy** [comment]
FabricAPI не ставили ведь сами вручную? Если что, он устанавливается автоматически, в новом обновлении добавлю уведомление об этом и возможность отключить. Попробуйте выбрать другую папку для игры, пустую, и установить туда Fabric 1.18.1 начисто

**Comment by Seeroy** [comment]
Рекомендации выше беру назад. Проблема найдена и исправлена, обновление будет сегодня

**Comment by Seeroy** [comment]
Проверьте, присутствует ли ошибка в данном обновлении
https://github.com/Seeroy/FrogLauncher/releases/tag/v1.0.5

**Comment by Belkin1337** [comment]
> Проверьте, присутствует ли ошибка в данном обновлении https://github.com/Seeroy/FrogLauncher/releases/tag/v1.0.5

Да, теперь всё без ошибок запускается. Спасибо

**Comment by Seeroy** [comment]
Вам спасибо за обратную связь. Если ещё что-то такое встретите - обязательно сообщите
